// Service page constants for better maintainability

export const SERVICE_PAGE_CONSTANTS = {
  // Display limits
  MAX_CITIES_SHOW: 10,
  MAX_MAIN_CITIES_SHOW: 8,
  MAX_NEARBY_CITIES: 4,
  MAX_PRICE_RANGES: 5,
  MAX_NEIGHBORHOODS: 8,
  MAX_SIMILAR_TRADES: 6,
  MAX_SERVICE_PAGES: 6,
  MAX_CATEGORIES_SHOW: 6,
  MAX_TRADES_PER_CATEGORY: 3,
  
  // Data fetching limits
  JOBS_LIMIT: 500,
  WORKER_CHUNK_SIZE: 50,
  
  // Time ranges (in days)
  METRICS_LOOKBACK_DAYS: 30,
  
  // Cache durations (in seconds)
  CACHE_REVALIDATE_CATEGORY: 1800, // 30 minutes
  CACHE_REVALIDATE_SERVICE: 1800,  // 30 minutes  
  CACHE_REVALIDATE_CITY: 3600,     // 1 hour
  
  // Pagination
  DEFAULT_PAGE_SIZE: 20,
  
  // Rating thresholds
  MIN_RATING_FOR_DISPLAY: 4.0,
  MIN_BUDGET_FOR_DISPLAY: 100,
  
  // Content lengths
  MAX_EXCERPT_LENGTH: 160,
  MAX_TITLE_LENGTH: 60,
} as const;

// Export individual constants for easier usage
export const {
  MAX_CITIES_SHOW,
  MAX_MAIN_CITIES_SHOW,
  MAX_NEARBY_CITIES,
  MAX_PRICE_RANGES,
  MAX_NEIGHBORHOODS,
  MAX_SIMILAR_TRADES,
  MAX_SERVICE_PAGES,
  MAX_CATEGORIES_SHOW,
  MAX_TRADES_PER_CATEGORY,
  JOBS_LIMIT,
  WORKER_CHUNK_SIZE,
  METRICS_LOOKBACK_DAYS,
  CACHE_REVALIDATE_CATEGORY,
  CACHE_REVALIDATE_SERVICE,
  CACHE_REVALIDATE_CITY,
  DEFAULT_PAGE_SIZE,
  MIN_RATING_FOR_DISPLAY,
  MIN_BUDGET_FOR_DISPLAY,
  MAX_EXCERPT_LENGTH,
  MAX_TITLE_LENGTH,
} = SERVICE_PAGE_CONSTANTS;
