/**
 * Top 100 orașe din România pentru SEO
 * Ordonate după populație și importanță economică
 */
export const romanianCities = [
  'București',
  'Cluj-Napoca',
  'Timișoara',
  'Iași',
  'Constanța',
  'Craiova',
  'Brașov',
  'Galați',
  'Ploiești',
  'Oradea',
  'Brăila',
  'Arad',
  'Pitești',
  'Sibiu',
  'Bacău',
  'Târgu Mureș',
  'Baia Mare',
  'Buzău',
  'Botoșani',
  'Satu Mare',
  'Râmnicu Vâlcea',
  'Suceava',
  'Piatra Neamț',
  'Drobeta-Turnu Severin',
  'Focșani',
  'Târgoviște',
  'Târgu Jiu',
  'Tulcea',
  'Reșița',
  'Bistrița',
  'Slatina',
  'Călărași',
  'Giurgiu',
  'Deva',
  'Hunedoara',
  'Zalău',
  'Alba Iulia',
  'Mediaș',
  'Vaslui',
  'Roman',
  'Turda',
  'Sfântu Gheorghe',
  'Bârlad',
  'Voluntari',
  'Câmpina',
  'Petroșani',
  'Lugoj',
  'Medgidia',
  'Onești',
  'Miercurea Ciuc',
  'Sighetu Marmației',
  'Mangalia',
  'Tecuci',
  'Pașcani',
  'Câmpulung',
  'Dej',
  'Reghin',
  'Năvodari',
  'Făgăraș',
  'Curtea de Argeș',
  'Caracal',
  'Mioveni',
  'Săcele',
  'Odorheiu Secuiesc',
  'Râmnicu Sărat',
  'Dorohoi',
  'Huși',
  'Câmpia Turzii',
  'Moreni',
  'Lupeni',
  'Vulcan',
  'Caransebeș',
  'Aiud',
  'Fetești',
  'Cernavodă',
  'Roșiorii de Vede',
  'Zimnicea',
  'Oltenița',
  'Turnu Măgurele',
  'Sebeș',
  'Blaj',
  'Codlea',
  'Gheorgheni',
  'Toplița',
  'Gherla',
  'Salonta',
  'Bocșa',
  'Marghita',
  'Carei',
  'Vatra Dornei',
  'Câmpulung Moldovenesc',
  'Rădăuți',
  'Fălticeni',
  'Moinești',
  'Comănești',
  'Buftea',
  'Popești-Leordeni',
  'Pantelimon',
  'Chitila',
];
