/**
 * Top 100 orașe din România pentru SEO
 * Ordonate după populație și importanță economică
 * 
 * NOTE: Sectoarele Bucureștiului sunt incluse pentru SEO local granular.
 * Fiecare sector are propria pagină pentru targeting mai precis.
 */
export const romanianCities = [
  'București',
  'Sectorul 1',
  'Sectorul 2',
  'Sectorul 3',
  'Sectorul 4',
  'Sectorul 5',
  'Sectorul 6',
  'Cluj-Napoca',
  'Timișoara',
  'Iași',
  'Constanța',
  'Craiova',
  'Brașov',
  'Galați',
  'Ploiești',
  'Oradea',
  'Brăila',
  'Arad',
  'Pitești',
  'Sibiu',
  'Bacău',
  'Târgu Mureș',
  'Baia Mare',
  'Buzău',
  'Botoșani',
  'Satu Mare',
  'Râmnicu Vâlcea',
  'Suceava',
  'Piatra Neamț',
  'Drobeta-Turnu Severin',
  'Focșani',
  'Vrancea',
  'Adjud',
  'Mărășești',
  'Panciu',
  'Târgoviște',
  'Dâmbovița',
  'Târgu Jiu',
  'Tulcea',
  'Reșița',
  'Bistrița',
  'Slatina',
  'Călărași',
  'Giurgiu',
  'Deva',
  'Hunedoara',
  'Zalău',
  'Alba Iulia',
  'Ocna Mureș',
  'Mediaș',
  'Vaslui',
  'Roman',
  'Turda',
  'Sfântu Gheorghe',
  'Slobozia',
  'Ialomița',
  'Bârlad',
  'Voluntari',
  'Câmpina',
  'Petroșani',
  'Lugoj',
  'Medgidia',
  'Onești',
  'Miercurea Ciuc',
  'Poiana Brașov',
  'Sighetu Marmației',
  'Mangalia',
  'Tecuci',
  'Pașcani',
  'Câmpulung',
  'Dej',
  'Reghin',
  'Năvodari',
  'Făgăraș',
  'Curtea de Argeș',
  'Caracal',
  'Mioveni',
  'Săcele',
  'Odorheiu Secuiesc',
  'Râmnicu Sărat',
  'Dorohoi',
  'Huși',
  'Câmpia Turzii',
  'Moreni',
  'Lupeni',
  'Vulcan',
  'Caransebeș',
  'Aiud',
  'Fetești',
  'Cernavodă',
  'Roșiorii de Vede',
  'Zimnicea',
  'Oltenița',
  'Turnu Măgurele',
  'Sebeș',
  'Blaj',
  'Codlea',
  'Gheorgheni',
  'Toplița',
  'Gherla',
  'Salonta',
  'Bocșa',
  'Marghita',
  'Carei',
  'Vatra Dornei',
  'Câmpulung Moldovenesc',
  'Rădăuți',
  'Fălticeni',
  'Moinești',
  'Comănești',
  'Buftea',
  'Popești-Leordeni',
  'Pantelimon',
  'Chitila',
];
